# Generated by Django 2.1.5 on 2020-04-11 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200411_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 20, 52, 32, 446107), verbose_name='date published'),
        ),
    ]
