# Generated by Django 2.1.5 on 2020-04-16 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200411_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('post_published', models.DateTimeField(default=datetime.datetime(2020, 4, 16, 14, 24, 49, 950922), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
